### PR TITLE
Added RemoteData type

### LINKED ISSUE #2: Add support for `RemoteData` type
Support for the `RemoteData` type from [this](https://github.com/devexperts/remote-data-ts) library would be fantastic

### PR DESCRIPTION
**Pull request by Brettm12345**
Added a `toRemoteData` function which uses the library [remote-data-ts](https://github.com/devexperts/remote-data-ts)

### CODE REVIEW

**Comment by tetsuo** [comment]
Hi @Brettm12345 

Thank you! `remote-data-ts` looks really interesting. 

But I think this requires you to add `dom` to tsconfig.json, which I'm really not sure about it. I don't really intend to use this library in browser.

**Comment by Brettm12345** [comment]
It doesn't look like the library uses the dom at all

**Comment by tetsuo** [comment]
It's in here, `ProgressEvent`:

https://github.com/devexperts/remote-data-ts/blob/master/src/remote-data.ts#L248

Actually it might be a good idea to move this to separate file in `remote-data-ts` module, then you don't need to add `dom` in tsconfig file in here.

**Comment by tetsuo** [comment]
Hey @Brettm12345 

I think this doesn't have any effect on dependencies unless `lib/remoteData.ts` is directly imported. So it's ok to merge this. But, can you add `dom` to list of libraries in `tsconfig.json` so build passes? Thanks a lot

**Comment by Brettm12345** [comment]
Done

**Comment by tetsuo** [comment]
Thank you!

Released `v1.1.0`  🎉

**Pull request merged**
